"""YAML-based configuration: agent config + benchmark config."""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

import yaml


# ---------------------------------------------------------------------------
# Agent config (shared across all benchmarks)
# ---------------------------------------------------------------------------

@dataclass
class ModelConfig:
    name: str
    base_url: str = "http://localhost:8000/v1"
    api_key: str = "EMPTY"
    temperature: float = 0.0
    max_tokens: int = 2048
    reasoning: bool = False


@dataclass
class AgentSettings:
    max_steps: int = 15
    time_budget: int = 300
    workers: int = 1


@dataclass
class AgentConfig:
    """Loaded from agent.yaml at project root."""

    model: ModelConfig
    agent: AgentSettings = field(default_factory=AgentSettings)
    system_prompt: str | None = None

    @classmethod
    def from_yaml(cls, path: str | Path) -> AgentConfig:
        raw = yaml.safe_load(Path(path).read_text())
        model = ModelConfig(**raw["model"])
        agent = AgentSettings(**raw.get("agent", {}))
        return cls(
            model=model,
            agent=agent,
            system_prompt=raw.get("system_prompt"),
        )


# ---------------------------------------------------------------------------
# Benchmark config (per-run, benchmark-specific)
# ---------------------------------------------------------------------------

@dataclass
class ParevalBenchmarkConfig:
    """Loaded from runs/<run-name>/config.yaml for ParEval runs."""

    problem_set: str = "omp"
    launch_configs: str | None = None
    build_timeout: int = 30
    run_timeout: int = 120

    @classmethod
    def from_yaml(cls, path: str | Path) -> ParevalBenchmarkConfig:
        raw = yaml.safe_load(Path(path).read_text())
        return cls(**raw)


@dataclass
class HeCBenchSerialGenConfig:
    """Loaded from runs/hecbench_serial_gen/<run-name>/config.yaml.

    Task framing: produce a serial C++ reference for each HeCBench
    benchmark by exposing every available parallel implementation
    (``<name>-cuda``, ``-omp``, ``-hip``, ``-sycl``) as a subdirectory
    of the agent's workspace and letting it iterate via tool calls.
    """

    # HeCBench src/ tree (each benchmark is at <src_root>/<name>-<variant>/).
    src_root: str = "benchmarks/HeCBench/src"
    # Path to benchmarks.yaml — used to discover candidate names + their
    # test args / regex / timeout / categories.
    benchmarks_yaml: str = "benchmarks/HeCBench/benchmarks.yaml"
    # Where the final serial corpus is written (consumed by run_hecbench.py).
    out_root: str = "benchmarks/HeCBench/serial_agent"
    # Allow-list filters — both optional.
    names: list[str] | None = None
    categories: list[str] | None = None
    # Skip benchmarks that don't have this variant. Set to null to accept
    # any benchmark with at least one variant.
    require_variant: str | None = "omp"

    @classmethod
    def from_yaml(cls, path: str | Path) -> HeCBenchSerialGenConfig:
        raw = yaml.safe_load(Path(path).read_text())
        return cls(**raw)


@dataclass
class HeCBenchBenchmarkConfig:
    """Loaded from runs/<run-name>/config.yaml for HeCBench runs.

    Task framing: given the serial C++ implementation at
    ``<serial_root>/<name>/main.cpp`` (pre-generated by
    ``scripts/gen_serial_hecbench.py``), produce a parallel version
    targeting ``target`` — one of ``cuda`` / ``omp`` / ``hip`` / ``sycl``.
    """

    # Which parallel model the agent should produce.
    target: str = "cuda"
    # Serial source root (per-benchmark main.cpp + .meta.json).
    serial_root: str = "benchmarks/HeCBench/serial"
    # Original HeCBench src/ tree — used only to locate reference
    # <name>-<target>/ dirs for baseline timing during eval.
    src_root: str = "benchmarks/HeCBench/src"
    # Allow-list filters — both optional.
    names: list[str] | None = None
    categories: list[str] | None = None
    # How many timed iterations autohecbench.py runs per benchmark.
    repeat: int = 5
    # CUDA compute capability for nvcc (e.g. 89 for RTX 4090, 80 for A100,
    # 90 for H100). Passed through to autohecbench as ``--nvidia-sm``.
    nvidia_sm: int = 89

    @classmethod
    def from_yaml(cls, path: str | Path) -> HeCBenchBenchmarkConfig:
        raw = yaml.safe_load(Path(path).read_text())
        return cls(**raw)
